version: "3.8" 

services: 

  postgres: 
    image: postgres
    container_name: rockingdata
    restart: always
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_PASSWORD=ejemplo
      - POSTGRES_USER=augusto
      - POSTGRES_DB=db_Docker
      - POSTGRES_HOST=localhost
    volumes:
      - postgres-data:/var/lib/pgsql/data

  pgadmin: 
    image: dpage/pgadmin4
    ports:
      - "90:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "amonza621@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "ejemplo"
    depends_on:
      - postgres

volumes:
  postgres-data: